import PartIWork

/-!
This is the public verification surface for the complete Part (i) solution.
It checks the maintained largest-prime statement, the original 1978
greatest-prime-power statement, and every promoted finite characterization.
-/

#check Erdos700PartI.f_eq_div_iff_boundarySafe
#check Erdos700PartI.f_eq_div_primePow_iff_boundarySafeAt
#check Erdos700PartI.erdos_700_i_historical
#check Erdos700PartI.erdos_700_i_historical_orderDual
#check Erdos700PartI.erdos_700_i_historical_extremal
#check Erdos700PartI.f_eq_div_iff_fullShadowSafe
#check Erdos700PartI.f_eq_div_iff_boundedObstructionSafe
#check Erdos700PartI.f_eq_div_iff_cofactorObstructionSafe
#check Erdos700PartI.f_eq_div_iff_divisorPosetSafe
#check Erdos700PartI.factorTableauFeasible_iff_exists_boundary_realized
#check Erdos700PartI.boundarySafeAt_iff_factorTableauSafe
#check Erdos700PartI.ExplicitTableau.borrowRow_iff_outgoing
#check Erdos700PartI.ExplicitTableau.borrowRow_iff_resultDigit
#check Erdos700PartI.ExplicitTableau.card_var_exact
#check Erdos700PartI.ExplicitTableau.card_var_le
#check Erdos700PartI.ExplicitG.G_to_factorTableauFeasible
#check Erdos700PartI.ExplicitG.factorTableauFeasible_to_G
#check Erdos700PartI.ExplicitG.explicitG_iff_factorTableauFeasible

#print axioms Erdos700PartI.residueCarryWeight_dvd_of_admissible
#print axioms Erdos700PartI.minimalOverweightDivisor_iff_boundary
#print axioms Erdos700PartI.lt_residueCarryWeight_iff_exists_boundary
#print axioms Erdos700PartI.dvd_residueCarryWeight_iff_carryInequalities
#print axioms Erdos700PartI.realized_iff_exists_dvd_residueCarryWeight
#print axioms Erdos700PartI.residueCarrySafe_iff_boundarySafe
#print axioms Erdos700PartI.f_eq_div_iff_boundarySafe
#print axioms Erdos700PartI.f_eq_div_primePow_iff_boundarySafeAt
#print axioms Erdos700PartI.erdos_700_i_historical
#print axioms Erdos700PartI.erdos_700_i_historical_orderDual
#print axioms Erdos700PartI.erdos_700_i_historical_extremal
#print axioms Erdos700PartI.f_eq_div_iff_fullShadowSafe
#print axioms Erdos700PartI.f_eq_div_iff_boundedObstructionSafe
#print axioms Erdos700PartI.f_eq_div_iff_cofactorObstructionSafe
#print axioms Erdos700PartI.f_eq_div_iff_divisorPosetSafe
#print axioms Erdos700PartI.factorTableauFeasible_iff_exists_boundary_realized
#print axioms Erdos700PartI.boundarySafeAt_iff_factorTableauSafe
#print axioms Erdos700PartI.ExplicitTableau.borrowRow_iff_outgoing
#print axioms Erdos700PartI.ExplicitTableau.borrowRow_iff_resultDigit
#print axioms Erdos700PartI.ExplicitTableau.card_var_exact
#print axioms Erdos700PartI.ExplicitTableau.card_var_le
#print axioms Erdos700PartI.ExplicitG.G_to_factorTableauFeasible
#print axioms Erdos700PartI.ExplicitG.factorTableauFeasible_to_G
#print axioms Erdos700PartI.ExplicitG.explicitG_iff_factorTableauFeasible
